name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/github_key
          chmod 600 ~/.ssh/github_key
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_key

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} -i ~/.ssh/github_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/sadmin/GameMonetaWebAppServer &&
          git stash &&
          git fetch origin main &&
          git reset --hard origin/main &&
          echo "${{ secrets.SERVER_SUDO_PASSWORD }}" | sudo -S systemctl restart gamemoneta-site.service
          EOF